# Generated by Django 5.2.1 on 2025-07-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningBalance',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.PositiveIntegerField()),
                ('date', models.DateField()),
                ('account_name', models.CharField(max_length=100)),
                ('sub_type', models.CharField(max_length=50)),
                ('debit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('action', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Opening Balance',
                'verbose_name_plural': 'Opening Balances',
            },
        ),
    ]
