# Generated by Django 5.2.1 on 2025-07-09 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openingbalance',
            old_name='year',
            new_name='financial_year',
        ),
    ]
